### ISSUE TITLE
使用 python requests 上传文件名包含中文问题

### ISSUE THREAD

**Issue by wyattguo** [sbzhu/weworkapi_python#1]
使用 requests 可以成功上传英文文件名的文件，但不能上传文件名包含中文的情况。
能否给出使用 requests 上传文件名包含中文的示例？

我目前的做法：
`f = open(u'测试.txt', 'rb')`
`url = '''https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=%s&type=file''' % ac_token`
`files = {'file': ('测试.txt', f)}`
`r = requests.post(url, files=files)`

返回的是
`{u'errcode': 44001, u'errmsg': u'empty media data, hint: [ ], more info at https://open.work.weixin.qq.com/devtool/query?e=44001'}`

看起来是 requests 将 Content-Disposition 部分写为了：
`Content-Disposition: form-data; name="file"; filename*=utf-8''%E6%B5%8B%E8%AF%95.txt`

使用 API [测试页面](http://work.weixin.qq.com/api/devtools/devtool.php) 可以成功上传中文文件名的文件，看到的 Request Payload 为：
`Content-Disposition: form-data; name="media"; filename="测试.txt"`

**Comment by sbzhu** [comment]
python 要使用中文，需要在 文件开头加 #coding=utf-8
